// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: payment.proto

package packets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentClient interface {
	// for adapter
	CreateCashIn(ctx context.Context, in *CreateCashInRequest, opts ...grpc.CallOption) (*CreateCashInResponse, error)
	CashInInquiry(ctx context.Context, in *CashInInquiryRequest, opts ...grpc.CallOption) (*CashInInquiryResponse, error)
	CashOutCallback(ctx context.Context, in *CashOutCallbackRequest, opts ...grpc.CallOption) (*CashOutCallbackResponse, error)
	// for recon
	TransactionAdjustment(ctx context.Context, in *TransactionAdjustmentRequest, opts ...grpc.CallOption) (*TransactionAdjustmentResponse, error)
	TransactionEnrollment(ctx context.Context, in *TransactionEnrollmentRequest, opts ...grpc.CallOption) (*TransactionEnrollmentResponse, error)
}

type paymentClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentClient(cc grpc.ClientConnInterface) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) CreateCashIn(ctx context.Context, in *CreateCashInRequest, opts ...grpc.CallOption) (*CreateCashInResponse, error) {
	out := new(CreateCashInResponse)
	err := c.cc.Invoke(ctx, "/packets.Payment/CreateCashIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) CashInInquiry(ctx context.Context, in *CashInInquiryRequest, opts ...grpc.CallOption) (*CashInInquiryResponse, error) {
	out := new(CashInInquiryResponse)
	err := c.cc.Invoke(ctx, "/packets.Payment/CashInInquiry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) CashOutCallback(ctx context.Context, in *CashOutCallbackRequest, opts ...grpc.CallOption) (*CashOutCallbackResponse, error) {
	out := new(CashOutCallbackResponse)
	err := c.cc.Invoke(ctx, "/packets.Payment/CashOutCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) TransactionAdjustment(ctx context.Context, in *TransactionAdjustmentRequest, opts ...grpc.CallOption) (*TransactionAdjustmentResponse, error) {
	out := new(TransactionAdjustmentResponse)
	err := c.cc.Invoke(ctx, "/packets.Payment/TransactionAdjustment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) TransactionEnrollment(ctx context.Context, in *TransactionEnrollmentRequest, opts ...grpc.CallOption) (*TransactionEnrollmentResponse, error) {
	out := new(TransactionEnrollmentResponse)
	err := c.cc.Invoke(ctx, "/packets.Payment/TransactionEnrollment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
// All implementations should embed UnimplementedPaymentServer
// for forward compatibility
type PaymentServer interface {
	// for adapter
	CreateCashIn(context.Context, *CreateCashInRequest) (*CreateCashInResponse, error)
	CashInInquiry(context.Context, *CashInInquiryRequest) (*CashInInquiryResponse, error)
	CashOutCallback(context.Context, *CashOutCallbackRequest) (*CashOutCallbackResponse, error)
	// for recon
	TransactionAdjustment(context.Context, *TransactionAdjustmentRequest) (*TransactionAdjustmentResponse, error)
	TransactionEnrollment(context.Context, *TransactionEnrollmentRequest) (*TransactionEnrollmentResponse, error)
}

// UnimplementedPaymentServer should be embedded to have forward compatible implementations.
type UnimplementedPaymentServer struct {
}

func (UnimplementedPaymentServer) CreateCashIn(context.Context, *CreateCashInRequest) (*CreateCashInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCashIn not implemented")
}
func (UnimplementedPaymentServer) CashInInquiry(context.Context, *CashInInquiryRequest) (*CashInInquiryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CashInInquiry not implemented")
}
func (UnimplementedPaymentServer) CashOutCallback(context.Context, *CashOutCallbackRequest) (*CashOutCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CashOutCallback not implemented")
}
func (UnimplementedPaymentServer) TransactionAdjustment(context.Context, *TransactionAdjustmentRequest) (*TransactionAdjustmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransactionAdjustment not implemented")
}
func (UnimplementedPaymentServer) TransactionEnrollment(context.Context, *TransactionEnrollmentRequest) (*TransactionEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransactionEnrollment not implemented")
}

// UnsafePaymentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServer will
// result in compilation errors.
type UnsafePaymentServer interface {
	mustEmbedUnimplementedPaymentServer()
}

func RegisterPaymentServer(s grpc.ServiceRegistrar, srv PaymentServer) {
	s.RegisterService(&Payment_ServiceDesc, srv)
}

func _Payment_CreateCashIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCashInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CreateCashIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Payment/CreateCashIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CreateCashIn(ctx, req.(*CreateCashInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_CashInInquiry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashInInquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CashInInquiry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Payment/CashInInquiry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CashInInquiry(ctx, req.(*CashInInquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_CashOutCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashOutCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CashOutCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Payment/CashOutCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CashOutCallback(ctx, req.(*CashOutCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_TransactionAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).TransactionAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Payment/TransactionAdjustment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).TransactionAdjustment(ctx, req.(*TransactionAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_TransactionEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).TransactionEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/packets.Payment/TransactionEnrollment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).TransactionEnrollment(ctx, req.(*TransactionEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Payment_ServiceDesc is the grpc.ServiceDesc for Payment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "packets.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCashIn",
			Handler:    _Payment_CreateCashIn_Handler,
		},
		{
			MethodName: "CashInInquiry",
			Handler:    _Payment_CashInInquiry_Handler,
		},
		{
			MethodName: "CashOutCallback",
			Handler:    _Payment_CashOutCallback_Handler,
		},
		{
			MethodName: "TransactionAdjustment",
			Handler:    _Payment_TransactionAdjustment_Handler,
		},
		{
			MethodName: "TransactionEnrollment",
			Handler:    _Payment_TransactionEnrollment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
